-- 1. Tạo bảng Registrations (Danh sách đăng ký ban đầu)
CREATE TABLE IF NOT EXISTS public.registrations (
    account text NOT NULL PRIMARY KEY,
    employee_name text NOT NULL,
    unit text NOT NULL,
    relatives text[] DEFAULT '{}'::text[]
);

-- Bật phân quyền Row Level Security (RLS)
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Tạo Policy cho phép đọc công khai (Read-only) bằng Anon Key
CREATE POLICY "Allow public read access on registrations" 
ON public.registrations 
FOR SELECT 
USING (true);

-- Tạo Policy cho phép Service Role ghi chèn dữ liệu
CREATE POLICY "Allow service_role full access on registrations" 
ON public.registrations 
FOR ALL 
TO service_role 
USING (true);


-- 2. Tạo bảng Bookings (Lịch sử đặt ghế)
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat text NOT NULL,
    name text NOT NULL,
    account text NOT NULL,
    unit text NOT NULL,
    cinema text NOT NULL,
    saved_at timestamp with time zone DEFAULT now() NOT NULL,
    
    -- Đảm bảo mỗi ghế tại một rạp chỉ được đặt tối đa một lần
    CONSTRAINT bookings_cinema_seat_key UNIQUE (cinema, seat)
);

-- Bật phân quyền Row Level Security (RLS)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Tạo Policy cho phép đọc công khai (Read-only)
CREATE POLICY "Allow public read access on bookings" 
ON public.bookings 
FOR SELECT 
USING (true);

-- Tạo Policy cho phép chèn dữ liệu công khai (Để CBNV đặt ghế)
CREATE POLICY "Allow public insert access on bookings" 
ON public.bookings 
FOR INSERT 
WITH CHECK (true);

-- Tạo Policy cho phép Service Role quản lý dữ liệu
CREATE POLICY "Allow service_role full access on bookings" 
ON public.bookings 
FOR ALL 
TO service_role 
USING (true);
